### ISSUE TITLE
CH-GEN-1 and MA-G8-1 not sending alerts to Alerta

### ISSUE THREAD

**Issue by riaandn1** [openvcloud/alertabot#10]
The following systems have the code installed but we are not seeing the systems appear in Alerta:  
- CH-GEN-1   
- MA-G8-1  

```
/# head /opt/jumpscale7/hrd/system/system.hrd
alerta.api_key                 = '0s5PFkJfGjIZvzR3kdkgS92gjGFOS7m9U8sV0S5B'
alerta.api_url                 = 'http://alerta.aydo.com:8000/api'

logging                        = '1'
```

**Comment by ashraffouda** [comment]
Not relevant, the implementation for how alerts are sent from ovc changed, should be ok with next update
