### ISSUE TITLE
AlertaBot not sending alarms to Telegram group

### ISSUE THREAD

**Issue by riaandn1** [openvcloud/alertabot#11]
The following alarm was raised by UK-LN-VT-1 on OVC and Alerta but alertabot failed to send message to tlegram group gig_monitoring_alerts.
![image](https://user-images.githubusercontent.com/31112145/34868698-8ef3099e-f77c-11e7-8310-0c5ebc79f020.png)
![image](https://user-images.githubusercontent.com/31112145/34868708-97d4fa90-f77c-11e7-89b7-581991a329f3.png)

**Comment by ashraffouda** [comment]
verified on 2.2.6 supposed to be working now

**Comment by Dinaamagdy** [comment]
verified on be-scale-2
```
JumpScale
Core: branch: 7.2.6 (39bfc82) 1/22/2018, 3:50:58 PM
Portal: branch: 7.2.6 (fffe2bf) 1/19/2018, 8:40:36 AM
OpenvCloud
Core: branch: 2.2.6_vfwstart_1251 (45ec5e9) 1/23/2018, 2:18:17 PM
G8VDC: tag: v2.2.5 (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: 2.2.6 (3a47ecb) 1/22/2018, 11:21:19 AM
```
