### ISSUE TITLE
Colour Coding of Alerta Alarms

### ISSUE THREAD

**Issue by riaandn1** [openvcloud/alertabot#4]
Please make sure that alarms are properly colour coded in alerta:  
* Critical (Error) = Red  
* Major (Warning) = Orange  
* Minor (Expired) = Yellow
* Acknowledged = Blue

**Comment by ashraffouda** [comment]
1- We only send Errors and warning to alerta we don't send `Expired` health checks to alerta
2- alerta is not supposed to have expired health check it should reflect current Errors and warnings in the env
3- ack is not a severity, ack is a status 
so as discussed with @riaandn1  I created an issue https://github.com/openvcloud/alertabot/issues/13  to create a `ack` filter in alerta to be able to list the acked alerts
