### ISSUE TITLE
Auto-clear alarms on Alerta

### ISSUE THREAD

**Issue by abaltazzis** [openvcloud/alertabot#6]
We need Alerta to get updated when an alarm clears itself and make sure that it gets closed on Alerta when the error condition no longer exists.

Notifications (emails / telegram) should also get updated for the clearing of each alarm.
Essentially, the alerta interface should only have open alarms that need handling.

**Comment by abaltazzis** [comment]
Based on a discussion with Asraf today with the following topic:

> for this issue https://github.com/openvcloud/alertabot/issues/6
> specially this part Notifications (emails / telegram) should also get updated for the clearing of each alarm.
> if i did this then u will get notification for flapping alerts and hence the telegram will be overwhelming again, since this needs to stop the deduplication feature of alerta 
> what I suggest is you get notification for new open alerts if they r not flapping and for flapping alerts we only update alerta dash board

Asraf will check the time intervals on which Alerta identifies an alarm as flapping so that we can decide which will be the best way to push recurring / flapping alarms.

**Comment by ashraffouda** [comment]
as agreed with @abaltazzis we will set the flapping frequency to 3 mins so if the alert changes it stauts more than 2 times in this period it will be considered flapping, and this alarm returns back after 3 mins it will be reported as a normal alarm agin

**Comment by Dinaamagdy** [comment]
verified on be-scale-2
